# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-03 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hentai2read_chapter',
            name='chapter_index',
            field=models.FloatField(default=0, verbose_name='章节索引'),
        ),
    ]
